option(LIBCPP "Use libc++ if compiler is clang" ON)
set(GLOBAL_COMPILE_OPTIONS "")
set(GLOBAL_LINK_OPTIONS "")

if (NOT EMSCRIPTEN)
    if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        if (LIBCPP)
            list(APPEND GLOBAL_COMPILE_OPTIONS $<$<COMPILE_LANGUAGE:CXX>:-stdlib=libc++>)
            list(APPEND GLOBAL_LINK_OPTIONS $<$<COMPILE_LANGUAGE:CXX>:-stdlib=libc++>)
            message(STATUS "Using Clang++ with libc++")
        else ()
            message(STATUS "Using Clang++ with stdlibc++")
        endif ()
    else ()
        message(STATUS "Using g++")
    endif ()
else ()
    message(STATUS "Using Emscripten.")
endif ()

add_compile_options(${GLOBAL_COMPILE_OPTIONS})
add_link_options(${GLOBAL_LINK_OPTIONS})
